package com.mycompany.practicafinalmtpa.cliente;

import com.mycompany.practicafinalmtpa.cliente.FrameCliente;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.io.DataOutputStream;
import java.io.IOException;
import javax.swing.*;

public class PanelSalones extends javax.swing.JPanel {
    private DefaultListModel<String> modeloUsuarios;
    private JList<String> usuariosConectados;
    private DataOutputStream salida;
    private JButton botonChatPrivado;

    /**
     * Creates new form PanelSalones
     */
    public PanelSalones(DataOutputStream salida) {
        initComponents();
        
        this.salida=salida;
        
        botonChatPrivado = new JButton("Chat privado");
        panelUsuarios.add(botonChatPrivado,BorderLayout.SOUTH);

        panelUsuarios.setLayout(new BorderLayout());
        
        modeloUsuarios= new DefaultListModel<>();
        usuariosConectados = new JList<>(modeloUsuarios);
        
        JScrollPane scrollUsuarios = new JScrollPane(usuariosConectados);
        panelUsuarios.add(scrollUsuarios,BorderLayout.CENTER);
    
         botonChatPrivado.addActionListener((ActionEvent e3) -> {
            iniciarChatPrivado();
        });
    }
    
    public void actualizarUsuarios(String[] usuarios){
    
        modeloUsuarios.clear();
        for(String u: usuarios){
            modeloUsuarios.addElement(u);
        }
        
    }
    
    private void iniciarChatPrivado(){
    
        String usuario= usuariosConectados.getSelectedValue();
        
        if(usuario==null){
            JOptionPane.showMessageDialog
        (this, "Selecciona un usuario");
            return;
        }
            try{
            
            salida.writeUTF("/crearChatPrivado " + usuario);
            salida.flush();
            }catch(IOException ex){
                System.out.println("No se pudo enviar el mensaje: "+ ex.getMessage());
            }
        
        }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSalones = new javax.swing.JScrollPane();
        listaSalones = new javax.swing.JList<>();
        BotonEntrarSalon = new javax.swing.JButton();
        panelUsuarios = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(750, 500));

        listaSalones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "IA", "Deportes", "Therian", "Manga", "UEMC" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        PanelSalones.setViewportView(listaSalones);
        listaSalones.getAccessibleContext().setAccessibleName("");

        BotonEntrarSalon.setLabel("Entrar");
        BotonEntrarSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });

        panelUsuarios.setMinimumSize(new java.awt.Dimension(59, 90));
        panelUsuarios.setPreferredSize(new java.awt.Dimension(59, 90));

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonEntrarSalon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(PanelSalones, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEntrarSalon)
                    .addComponent(PanelSalones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        
        String salonSeleccionado= listaSalones.getSelectedValue();

        if(salonSeleccionado==null){
        JOptionPane.showMessageDialog
        (this, "Selecciona un salon primero");
        return;
        }
        FrameCliente frameClientes = 
            (FrameCliente)SwingUtilities.getWindowAncestor(this);
        frameClientes.mostrarChatSalon(salonSeleccionado);
    }//GEN-LAST:event_botonEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrarSalon;
    private javax.swing.JScrollPane PanelSalones;
    private javax.swing.JList<String> listaSalones;
    private javax.swing.JPanel panelUsuarios;
    // End of variables declaration//GEN-END:variables
}
