package com.mycompany.practicafinalmtpa;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class PanelSalones extends javax.swing.JPanel {

    /**
     * Creates new form PanelSalones
     */
    public PanelSalones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSalones = new javax.swing.JScrollPane();
        listaSalones = new javax.swing.JList<>();
        BotonEntrarSalon = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 500));

        listaSalones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "IA", "Deportes", "Therian", "Manga", "UEMC" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        PanelSalones.setViewportView(listaSalones);
        listaSalones.getAccessibleContext().setAccessibleName("");

        BotonEntrarSalon.setLabel("Entrar");
        BotonEntrarSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonEntrarSalon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSalones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(566, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEntrarSalon)
                    .addComponent(PanelSalones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(394, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        
        String salonSeleccionado= listaSalones.getSelectedValue();

        if(salonSeleccionado==null){
        JOptionPane.showMessageDialog
        (null, "Selecciona un salon primero");
        return;
        }
        FrameCliente frameClientes = 
            (FrameCliente)SwingUtilities.getWindowAncestor(this);
        frameClientes.mostrarChatSalon(salonSeleccionado);
    }//GEN-LAST:event_botonEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrarSalon;
    private javax.swing.JScrollPane PanelSalones;
    private javax.swing.JList<String> listaSalones;
    // End of variables declaration//GEN-END:variables
}
